### ISSUE TITLE
Add new video to home page

### ISSUE THREAD

**Issue by lokioatmeal** [concordis/public-website#67]
- The new video should replace the first two sections on the home page—Concordis Way and Recruiting Process.
- h1 and main menu will remain atop the page.
- Remove unused images from removed sections afterward.
- Video should be 100% width and auto height.
- Initially, set this up to loop a portion at your discretion with audio off. Start and play in its entirety with audio on when a user clicks on it.
- We will likely revisit the looping portion after we see it in place.

**Comment by lokioatmeal** [comment]
Changes to address this issue have been committed. Please note that instead of drawing the video with a portion in a loop, I instead draw a static section, check to ensure the user can play the video, then draw a Play Video button. If the user clicks the Play Video button, the video starts loading, the static section fades out, and finally the video section fades in. When the video reaches ~1:45, it stops, its section fades out, and the static section fades back in.

I am keeping this issue open since we will likely need to make changes.

**Comment by lokioatmeal** [comment]
Feedback regarding the current video implementation is… redo it to act more like the video on the Pathwise website. Meaning:

1. Have video muted and running in a loop *under* the Play Video CTA onload.
2. If user chooses to click the Play button, launch video hosted on YouTube in a lightbox.
3. Note for iPhone at least, use a static image background that is a screenie of the video. For now, use the frame that shows the No Awkward Secrets text with the three illustrations.

**Comment by concordis** [comment]
Yes. The same behavior the Pathwise has on web and mobile web is ideal
[cid:DA3BF09F-B606-40B1-82AF-40A5641F87D9]<http://www.concordis.net>
  Brad Coulter
   Managing Partner/Co-Founder
   C: (206) 391-1271 O: (206) 347-8511
[cid:9DBD0BDA-2CC3-4B92-B07C-0AA2A890C2B9]<https://youtu.be/umuhXxasFrs> [cid:BC7964F1-12F4-47FF-88CF-B4B16E2CD070] <https://www.linkedin.com/company/concordis-llc>   [cid:5A4CD1A4-BF51-4C6D-8E87-BFF383C91FAA] <https://www.facebook.com/concordisllc/>   [cid:7C2C4814-F8CA-41E3-B548-4903A21D2CEB] <https://twitter.com/concordisjobs>




Feedback regarding the current video implementation is... redo it to act more like the video on the Pathwise website. Meaning:

  1.  Have video muted and running in a loop under the Play Video CTA onload.
  2.  If user chooses to click the Play button, launch video hosted on YouTube in a lightbox.
  3.  Note for iPhone at least, use a static image background that is a screenie of the video. For now, use the frame that shows the No Awkward Secrets text with the three illustrations.

-
